---
- hosts: all
  vars:
  vars_prompt:
    - name: "github_username"
      prompt: "\n\nEnter your github.com account.\n\nUsername"
      private: false
    - name: "github_password"
      prompt: "\nPassword"
      private: true

- hosts: develop
  roles:
    - develop
