---
- name: see if fzf exists or not
  stat: path={{ local_home }}/.fzf
  register: fzf

- name: if fzf dir has existed, uninstall fzf
  shell: |
      {{ local_home }}/.fzf/uninstall
      rm -rf {{ local_home }}/.fzf
  when: fzf.stat.exists

- name: git clone fzf
  git: repo=https://github.com/junegunn/fzf.git
       dest={{ local_home }}/.fzf
       depth=1

- name: install fzf
  command: ./install
  args:
      chdir: "{{ local_home }}/.fzf/"

- name: add path for fzf
  lineinfile:
    dest="{{ local_home }}/.zshrc.local"
    line="{{ item }}"
    owner={{ local_user }}
    state=present
    insertafter=EOF
    create=True
  with_items:
    - "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh"
