---
- name: check go modules status
  command: go list {{ item }}
  register: go_module
  failed_when: go_module.rc not in [0, 1]
  changed_when: go_module.rc not in [0, 1]
  with_items:
    - github.com/nsf/gocode
    - github.com/golang/lint
    - github.com/peco/peco/cmd/peco
    - github.com/motemen/ghq
  environment:
    GOPATH: "{{ local_home }}/go"
    PATH: "{{ lookup('env', 'PATH') }}:{{ prefix }}/go/{{ go_version }}/bin"

- name: install go modules
  command: go get {{ item.item }}
  when: item.rc  == 1
  with_items: go_module.results
  environment:
    GOPATH: "{{ local_home }}/go"
    PATH: "{{ lookup('env', 'PATH') }}:{{ prefix }}/go/{{ go_version }}/bin"
