---
- name: download Go
  become: yes
  get_url: url={{ go_dl_location }}
           force=yes
           dest=/tmp
           mode=0644
           checksum={{ go_sha1checksum }}

- name: mkdir Go's dir
  become: yes
  file: path={{ prefix }}/go
        state=directory
        owner={{ local_user }}
        group={{ local_user }}
        mode=0755

- name: unzip a Go archive
  become: yes
  command: tar xzf /tmp/{{ go_tar_ball }} -C {{ prefix }}/go

- name: remove Go current version's dir if exists
  become: yes
  file: path={{ prefix }}/go/{{ go_version }}
        state=absent

- name: rename Go install directory name
  become: yes
  command: mv {{ prefix }}/go/go {{ prefix }}/go/{{ go_version }}

- name: change dir and files permission
  become: yes
  file: path={{ prefix }}/go/{{ go_version }}
        state=directory
        mode=0755
        recurse=yes

- name: mkdir GOPATH dir
  file: path={{ local_home }}/go
        state=directory
        owner={{ local_user }}
        group={{ local_user }}
        mode=0755

- name: add path for Go
  lineinfile:
    dest="{{ local_home }}/.zshrc.local"
    line="{{ item }}"
    owner={{ local_user }}
    state=present
    insertafter=EOF
    create=True
  with_items:
    - "export GOROOT={{ prefix }}/go/{{ go_version }}"
    - "export PATH=$GOROOT/bin:$PATH"
    - "export GOPATH={{ local_home }}/go"
    - "export PATH=$GOPATH/bin:$PATH"
