---
- name: remove prezto's dir if exists
  become: yes
  file: path={{ local_home }}/.zprezto
        state=absent

- name: git clone Prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git
       dest={{ local_home }}/.zprezto
       update=yes
       recursive=yes
