---
- name: install tmux dependencies
  become: yes
  apt: name={{ item }}
       install_recommends=no
       update_cache=yes
       state=present
  with_items:
    - libevent-dev
    - ncurses-dev
    - build-essential
    - automake
    - pkg-config

- name: remove tmux src's dir if exists
  become: yes
  file: path={{ prefix }}/src/tmux
        state=absent

- name: git clone tmux
  become: yes
  git: repo=https://github.com/tmux/tmux.git
       dest={{ prefix }}/src/tmux

- name: autogen.sh
  become: yes
  command: ./autogen.sh
  args:
      chdir: "{{ prefix }}/src/tmux/"

- name: configure tmux
  become: yes
  command: ./configure --prefix={{ prefix }}
  args:
    chdir: "{{ prefix }}/src/tmux/"

- name: build tmux
  become: yes
  command: make
  args:
    chdir: "{{ prefix }}/src/tmux/"

- name: install tmux
  become: yes
  command: make install
  args:
    chdir: "{{ prefix }}/src/tmux/"
