---
- name: add git-core ppa
  become: yes
  apt_repository: repo='ppa:git-core/ppa'

- name: install git
  become: yes
  apt: name={{ item }}
       install_recommends=no
       update_cache=yes
       state=present
  with_items:
    - git-core
    - git
    - git-doc

- name: install mercurial
  become: yes
  apt: name=mercurial
       install_recommends=no
       update_cache=yes
       state=present
