---
- name: install zsh
  become: yes
  apt: name={{ item }}
       install_recommends=no
       update_cache=yes
       state=present
  with_items:
    - zsh

- name: touch .zshrc.local
  command: touch {{ local_home }}/.zshrc.local

- name: change login shell
  become: yes
  user: name={{ local_user }} state=present shell=/usr/bin/zsh
