---
- name: install zsh
  become: yes
  apt: name={{ item }}
       install_recommends=no
       update_cache=yes
       state=present
  with_items:
    - zsh

- name: touch .zshrc.local
  file: path={{ local_home }}/.zshrc.local
        state=touch
        mode=0644

- name: change login shell
  become: yes
  shell: chsh -s /usr/bin/zsh {{ local_user }}

#- name: change login shell
#  become: yes
#  user: name={{ local_user }} state=present shell=/usr/bin/zsh
